### PR TITLE
New commandline option 'verbosity' to allow different log levels

### PR DESCRIPTION
**Pull request by dmlambea**
Verbosity levels 0 (none), 1 (info) and 2 (extra) are supported. Current option 'quiet' is kept for backwards compatibility. It has been mapped to the new 'verbosity' values 0 (--quiet=true) and 1 (--quiet=false).

### CODE REVIEW

**Comment by ashkulz** [comment]
Looks good to me, but I think the description is incorrect. It should be
```
0 - no messages
1 - errors only
2 - warnings and errors
```
Also, making the default verbosity to 1 is a behavioral change, as it was previously 2. I think it'd be better to use an enum Verbosity with 3 values: Silent, Errors, WarningsAndErrors. Then, introduce a new command-line flag (`--silent`) which sets the verbosity to silent. Then, using both flags won't be an error: the last value wins. Your approach for backward compatibility can still be used, and is perfect -- you got it right :+1:

**Comment by dmlambea** [comment]
I'd turn verbosity INTs into level names (--loglevel), if you think it's more appropriate: e.g., 0 would become 'silent', 1 -> 'error', 2 -> 'warn', 3 -> 'info' (which are ready to add more levels, like 'debug', if needed someday). As cumulative levels, 'warn' would include 'error' as well as 'info' would include 'warn' and 'error'. To keep behavior unchanged, the default '--loglevel' would be 'info' and the effect of using '--quiet' would be to set '--loglevel' to 'silent' (or 'none', as it's shorter, if it is Ok to you). The bindings would be enhanced with a new callback for leveled logging while keeping backwards compatibility.

I don't see the command-line flag '--silent' in the final picture, since both '--quiet' and '--loglevel silent' lead to the same behavior. If using '--quiet' and '--loglevel' other than 'silent': the last value wins.

Is this all Ok?

**Comment by ashkulz** [comment]
Perfect :+1:

**Comment by ashkulz** [comment]
Thanks for the contribution!

**Comment by dmlambea** [comment]
Thanks to you! Keep up the good work!

**Comment by ashkulz** [comment]
A release candidate [is available](https://wkhtmltopdf.org/downloads.html#release-candidate) which includes the fixes made in this PR -- please test and report your findings before the final release.

**Pull request merged**
