### PR TITLE
Fixed issue in build for posix local

### PR DESCRIPTION
**Pull request by johnnadratowski**
Build failing for posix local without qtdir variable.

### CODE REVIEW

**Comment by ashkulz** [comment]
Why are you using the posix-local build?

**Comment by johnnadratowski** [comment]
@ashkulz - I'm building on Arch linux.  The AUR package for wkhtmltopdf doesn't have the patched Qt and I needed the extra functionality.  After these updates the package successfully built and worked properly.  Is the posix-local build target supposed to be unsupported?

**Comment by ashkulz** [comment]
Not really, but for Linux it would be obsoleted by the generic linux builds. Can you try the testing builds on the downloads page and see if they work for you?

Also, why did you need quotes around file paths?

**Comment by johnnadratowski** [comment]
@ashkulz - I'm not sure I understand... which generic build are you referring to?  The downloads page states that there are no generic linux builds because of package paths, which makes sense.  I don't see an Arch build on there, and it explicitly states that I would need to build it myself.  In the instructions for the build it says to use posix-local. Perhaps this is a documentation bug? :-)

The unquoted paths did not work on my system.  This was related to the file paths containing single quotes.  Also there was a variable referenced that was undefined.

**Comment by ashkulz** [comment]
Download 64-bit linux build under testing. Until it gets released, I'm leaving the disclaimers though it **is** confusing.

How did you get a quote in the machine name?

**Comment by johnnadratowski** [comment]
Ah, great, thanks.  I downloaded the binary and it worked.  I just checked the build path for wkhtmltopdf on my local and this is what I saw:

```
john@wilykit [09:05:14] [~/wkhtmltopdf/static-build/posix-local] [master *]
 ➜  ls
app/  qt/  wkhtmltox-0.12.3-dev-b'79ff51e'/
```

it seems like ti was taking the git hash or something, and putting it into single quotes.

**Comment by ashkulz** [comment]
What does `git rev-parse --short HEAD` return? Also, have you modified the contents of the `VERSION` file?

**Comment by johnnadratowski** [comment]
```
john@wilykit [10:46:26] [~/wkhtmltopdf] [master *]
 ➜  git rev-parse --short HEAD
79ff51e
```

I did not update the VERSION file.

**Comment by ashkulz** [comment]
Hmm, let me think. Are you using Python 3? I've only tested with Python 2.7 so that 'b' could indicate bytes.

**Comment by johnnadratowski** [comment]
You nailed it, I am using Python 3.

**Comment by ashkulz** [comment]
Hmm, let me try running the build script under Python3 and see what breaks. Closing this pull request as the error is really something else (machine/folder names are not going to have quotes otherwise).

**Pull request closed without merging**
