### PR TITLE
Resolve external links (handling relative links different according to flag)

### PR DESCRIPTION
**Pull request by KAYLukas**
Added a flag --resolve-external-links, to make it possible to resolve all relative links in the html document to absolute links.

Solves issue #1843.

### CODE REVIEW

**Comment by ashkulz** [comment]
Please change the commit message so that it fits within 65 characters and includes a fixes tag, see e02ff7efaf7b617986fc11c08a693e203c64a465. An entry in `CHANGELOG.md` is also recommended -- please squash & rebase it on top of the current `master`.

**Comment by ashkulz** [comment]
@KAYLukas: any update?

**Comment by KAYLukas** [comment]
Ah sorry, I see that I missed your comments, but I will try to process your comments this sunday.

**Comment by ashkulz** [comment]
Looking forward to it. Please squash and rebase your changes against the latest `master` so that I can do a [fast-forward merge](http://ariya.ofilabs.com/2013/09/fast-forward-git-merge.html).

**Comment by KAYLukas** [comment]
@ashkulz I have processed your comments and you should be able to fast forward merge my changes.

**Comment by ashkulz** [comment]
Thank you for the contribution!

**Comment by polomoshnov** [comment]
Perhaps you're using an older version. Support for relative links has been added in v0.12.3 which is unreleased as of now. You should build it yourself in accordance with the instructions given at https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/INSTALL.md

**Pull request merged**
