### PR TITLE
Fix unicode URLs, added ISO date template

### PR DESCRIPTION
**Pull request by theirix**
Store in hashmap strings parsed from percent-encoded unicode URLs.
Added internationalized 'isodate' template besides of locale-dependent date.

We use wkhtmltopdf in cross-language web project with cyrillic and english urls. This patch fixes behaviour of wkhtmltopdf with percent-encoded urls. They are gathered from body as unicode strings but are read from argument list as percent-encoded strings.

Another portion of patch added a template 'isodate' because webserver system locale where wkhtmltopdf is launched is not always a good choose.

### CODE REVIEW

**Comment by ashkulz** [comment]
A release candidate [0.12.2-rc-71e97c1](http://wkhtmltopdf.org/downloads.html#testing) is available, which has this change. Please report back if you encounter an issue with the above build.

**Comment by ashkulz** [comment]
`0.12.2` has been released, which includes changes related to this issue.

**Comment by vicancy** [comment]
Hi @ashkulz is the latest version containing the fix? I can still repro the issue with the latest `0.12.4`:
1. Create a localized file, e.g. ТестоваяСтраница.html
2. Create the main file main.html containing:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<title>title</title>
</head>
<body>
<p>Ссылка на <a href="%D0%A2%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D0%B0%D1%8F%D0%A1%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0.html">
	ТестоваяСтраница</a></p>
</body>
</html>
```
3. Convert: `wkhtmltopdf main.html ТестоваяСтраница.html test.pdf`
4. `test.pdf` is generated, however the link is not correctly resolved, it still link to an external link.

**Comment by theirix** [comment]
@vicancy , I just installed a 0.12.4 version from the https://github.com/wkhtmltopdf/wkhtmltopdf/releases/tag/0.12.4 page to the Debian 9 docker container. Your test works fine. Do you use binary from the github or from the OS repository?

**Comment by vicancy** [comment]
Hi @theirix I tried the github version however with no luck 😢  Is the fix has specific requirements on OS region or locale settings? I am using en-US as the default locale, doubt if that matters.

**Comment by theirix** [comment]
Maybe your locale is not UTF-8? Could you please post the `locale` and `locale -a` output? What is your OS?

Mine locale on Debian 9 is:
```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
On a Debian system UTF-8 locale can be added via `localedef -i en_US -c -f UTF-8 en_US.UTF-8` call. Reproducible test - https://gist.github.com/theirix/0876a5047a7da5da961444d2fd78c2e7

**Comment by vicancy** [comment]
@theirix I am on Windows... 😭

**Comment by theirix** [comment]
@vicancy I'm afraid I cannot check it quickly. I'll try to check it this Saturday.

**Comment by theirix** [comment]
@vicancy this issue is really reproducible on Windows (tried 7 x64) even with a Russian locale. So my fix doesn't work for Windows. Unfortunately I have no enough expertise in Windows and QT to fix this quickly.

**Pull request merged**
