### PR TITLE
Support non-standard install location on Mac OS

### PR DESCRIPTION
**Pull request by nickgaya**
Re-opening https://github.com/wkhtmltopdf/wkhtmltopdf/pull/3022 for further discussion.

These changes come from the [MacPorts port of wkhtmltopdf](https://ports.macports.org/port/wkhtmltopdf/) to resolve issues that arise when installing wkhtmltopdf to a non-default location (such as the MacPorts installation prefix). For more details, see the individual commit messages.

Cc @ashkulz @neverpanic

### CODE REVIEW

**Comment by ashkulz** [comment]
@nickgaya according to [your report on MacPorts](https://trac.macports.org/ticket/61149) there is a segfault? Please confirm if the changes work for you, as that's not a configuration which is checked by the CI.

Also, can you merge the latest `master`? I didn't see the detailed commit messages, sorry about that @neverpanic 🙈

**Comment by nickgaya** [comment]
@ashkulz I can confirm these patches work for the existing MacPorts port which is based on wkhtmltopdf 0.12.3.2.  I haven't tried debugging the segfault for 0.12.6 but I don't think it's related to these changes.

**Comment by ashkulz** [comment]
Can you check the segfault with the `.pkg` and see if it's a problem there as well?

**Comment by ashkulz** [comment]
Thanks for the contribution!

**Pull request merged**
