### PR TITLE
Fix all page-sizes documentation URL

### PR DESCRIPTION
**Pull request by NicoVogel**
I was searching for the full list of all supported page-sizes and noticed that the link was no longer correct.

### CODE REVIEW

**Review by ashkulz — CHANGES_REQUESTED** [review]
Please make changes in `src/pdf/pdfdocparts.cc` as this is a generated file. I can see multiple references to `qt-project.org` to comments in `src/lib/multipageloader.cc` as well, would appreciate updating those as well :+1:

**Comment by NicoVogel** [comment]
@ashkulz I updated all the links in `src/pdf/pdfdocparts.cc`, but the links in `src/lib/multipageloader.cc` still work, hence no change there.

**Review by ashkulz — APPROVED** [review]
Thanks for the contribution!

**Comment by ashkulz** [comment]
Builds are failing due to conan-io/conan-center-index#4151 -- I think it's safe to ignore :crossed_fingers:

**Pull request merged**
